// frontend-react/src/components/ServingsFilter.tsx
import type React from 'react';

interface ServingsFilterProps {
  servings: number;
  onServingsChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
}

const ServingsFilter: React.FC<ServingsFilterProps> = ({ servings, onServingsChange }) => {
  return (
    <div className="servings-filter">
      <label htmlFor="servings">Servings:</label>
      <div className="servings-selector">
        <button type="button" className="primary-button small-button decrement">-</button>
        <input
          className="input-number"
          type="number"
          id="servings"
          value={servings}
          min="1"
          max="6"
          onChange={onServingsChange}
        />
        <button type="button" className="primary-button small-button increment">+</button>
      </div>
    </div>
  );
};

export default ServingsFilter;

// frontend-angular/src/app/features/recipes/recipe-detail/recipe-section/recipe-instructions/servings-filter/servings-filter.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-servings-filter',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: 'servings-filter.component.html',
})
export class ServingsFilterComponent {
  @Input() servings = 1;
  @Output() servingsChange = new EventEmitter<number>();

  increaseServings(): void {
    if (this.servings < 12) {
      this.servings++;
      this.onServingsChange();
    }
  }

  decreaseServings(): void {
    if (this.servings > 1) {
      this.servings--;
      this.onServingsChange();
    }
  }

  onServingsChange(): void {
    this.servingsChange.emit(this.servings);
  }
}

<div class="servings-filter">
  <label for="servings">Servings:</label>
  <div class="servings-selector">
    <button class="primary-button small-button decrement" (click)="decreaseServings()">-</button>
    <input
      class="input-number"
      type="number"
      id="servings"
      [(ngModel)]="servings"
      min="1"
      max="12"
      (ngModelChange)="onServingsChange()">
    <button class="primary-button small-button increment" (click)="increaseServings()">+</button>
  </div>
</div>
