// frontend-angular/src/app/features/home/hero-section/hero-section.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { Subscription } from 'rxjs';
import { AuthStoreService } from '@core/store/auth-store.service';
import { AppImageComponent } from '@shared/components/app-image/app-image.component';
import { SearchBarComponent } from '@shared/components/search-bar/search-bar.component';

@Component({
  selector: 'app-hero-section',
  templateUrl: './hero-section.component.html',
  standalone: true,
  imports: [
    CommonModule,
    AppImageComponent,
    SearchBarComponent
  ],
})
export class HeroSectionComponent implements OnInit, OnDestroy {
  initialSearchQuery = '';
  isAuthenticated = false;
  userName: string | null = null;

  private subscriptions = new Subscription();

  constructor(
    private router: Router,
    public authStore: AuthStoreService
  ) {}

  ngOnInit(): void {
    this.subscriptions.add(
      this.authStore.isAuthenticated$.subscribe(isAuth => {
        this.isAuthenticated = isAuth;
      })
    );

    this.subscriptions.add(
      this.authStore.user$.subscribe(user => {
        this.userName = user?.name || null;
      })
    );
  }

  onSearchPerformed(query: string) {
    this.router.navigate(['/search'], { queryParams: { query } });
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }
}

<section class="hero">
  <app-image
    src="/logo.png"
    alt="logo"
    [width]="120"
    [height]="120"
    cssClass="app-logo"
  ></app-image>

  <h1 *ngIf="!isAuthenticated">Welcome to <span class="primary-text">Gastro</span><span class="secondary-text">Nest</span></h1>
  <h1 *ngIf="isAuthenticated">Welcome {{ userName }} to <span class="primary-text">Gastro</span><span class="secondary-text">Nest</span></h1>

  <p>Discover new recipes and save your favorites in your own recipe nest!</p>

  <app-search-bar
    placeholder="Search for recipes..."
    buttonText="Search"
    buttonType="tertiary"
    [initialQuery]="initialSearchQuery"
    (search)="onSearchPerformed($event)"
  ></app-search-bar>
</section>

// frontend-react/src/components/HeroSection.tsx
import type React from 'react';
import { useAuth } from '../context/AuthContext';
import SearchBar from '../components/SearchBar';
import Image from './Image';
import logo from '@assets/icons/logo.png';

const HeroSection: React.FC = () => {
  const { user } = useAuth();

  return (
    <section className="hero">
      <Image className="app-logo" src={logo} alt="logo" />
      <h1>
        Welcome {user ? user.name.split(' ')[0] : ""} to <span className="primary-text">Gastro</span>
        <span className="secondary-text">Nest</span>
      </h1>
      <p>
        Discover new recipes and save your favorites in your own recipe nest!
      </p>
      <SearchBar placeholder="Search for recipes..." />
    </section>
  );
};

export default HeroSection;
