// frontend-angular/src/app/features/home/components/hero-section/hero-section.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AppImageComponent } from '@shared/components/app-image/app-image.component';
import { SearchBarComponent } from '@shared/components/search-bar/search-bar.component';

@Component({
  selector: 'app-hero-section',
  templateUrl: './hero-section.component.html',
  standalone: true,
  imports: [
    CommonModule,
    AppImageComponent,
    SearchBarComponent
  ],
})
export class HeroSectionComponent {
  initialSearchQuery = '';

  constructor(private router: Router) {}

  onSearchPerformed(query: string) {
    this.router.navigate(['/search'], { queryParams: { query } });
  }
}

<section class="hero">
  <app-image
    src="/logo.png"
    alt="logo"
    [width]="120"
    [height]="120"
    cssClass="app-logo"
  ></app-image>

  <h1>Welcome to <span class="primary-text">Gastro</span><span class="secondary-text">Nest</span></h1>
  <p>Discover new recipes and save your favorites in your own recipe nest!</p>

  <app-search-bar
    placeholder="Search for recipes..."
    buttonText="Search"
    buttonType="tertiary"
    [initialQuery]="initialSearchQuery"
    (search)="onSearchPerformed($event)"
  ></app-search-bar>
</section>

// frontend-react/src/components/HeroSection.tsx
import type React from 'react';
import SearchBar from '../components/SearchBar';
import Image from './Image';
import logo from '@assets/icons/logo.png';

const HeroSection: React.FC = () => {
  return (
    <section className="hero">
      <Image className="app-logo" src={logo} alt="logo" />
      <h1>
        Welcome to <span className="primary-text">Gastro</span>
        <span className="secondary-text">Nest</span>
      </h1>
      <p>
        Discover new recipes and save your favorites in your own recipe nest!
      </p>
      <SearchBar placeholder="Search for recipes..." />
    </section>
  );
};

export default HeroSection;
