// frontend-angular/src/app/shared/components/pagination/pagination.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AppButtonComponent } from '@shared/components/app-button/app-button.component';
import { DropdownComponent } from '@shared/components/dropdown/dropdown.component';
import { FilterOption } from '@models/filter.model';

@Component({
  selector: 'app-pagination',
  templateUrl: './pagination.component.html',
  standalone: true,
  imports: [CommonModule, AppButtonComponent, DropdownComponent]
})
export class PaginationComponent {
  @Input() currentPage = 1;
  @Input() totalPages = 1;
  @Input() pageSize = 10;

  @Output() pageChange = new EventEmitter<number>();
  @Output() pageSizeChange = new EventEmitter<number>();

  pageSizeOptions: FilterOption[] = [
    { value: '10', label: '10' },
    { value: '20', label: '20' },
    { value: '50', label: '50' }
  ];

  onFirstPage(): void {
    if (this.currentPage !== 1) {
      this.pageChange.emit(1);
    }
  }

  onPreviousPage(): void {
    if (this.currentPage > 1) {
      this.pageChange.emit(this.currentPage - 1);
    }
  }

  onNextPage(): void {
    if (this.currentPage < this.totalPages) {
      this.pageChange.emit(this.currentPage + 1);
    }
  }

  onLastPage(): void {
    if (this.currentPage !== this.totalPages) {
      this.pageChange.emit(this.totalPages);
    }
  }

  onPageSizeChange(size: string): void {
    const newSize = Number.parseInt(size, 10);
    if (newSize !== this.pageSize) {
      this.pageSizeChange.emit(newSize);
    }
  }
}

<div class="pagination">
  <div class="navigation">
    <app-button
      type="secondary"
      size="medium"
      [disabled]="currentPage === 1"
      (buttonClick)="onFirstPage()">
      &lt;&lt;
    </app-button>

    <app-button
      type="primary"
      size="medium"
      [disabled]="currentPage === 1"
      (buttonClick)="onPreviousPage()">
      &lt;
    </app-button>

    <span class="page-info">Page {{ currentPage }} of {{ totalPages }}</span>

    <app-button
      type="primary"
      size="medium"
      [disabled]="currentPage === totalPages"
      (buttonClick)="onNextPage()">
      &gt;
    </app-button>

    <app-button
      type="secondary"
      size="medium"
      [disabled]="currentPage === totalPages"
      (buttonClick)="onLastPage()">
      &gt;&gt;
    </app-button>
  </div>

  <div class="filter results-filter">
    <label for="results-per-page">Results per page:</label>
    <app-dropdown
      id="results-per-page"
      [options]="pageSizeOptions"
      [selectedValue]="pageSize.toString()"
      [dropUp]="true"
      (valueChange)="onPageSizeChange($event)">
    </app-dropdown>
  </div>
</div>

// frontend-react/src/components/Pagination.tsx
import type React from 'react';
import '@styles/components/_pagination.scss';
import Button from './Button';
import Dropdown from './Dropdown';

const Pagination: React.FC = () => {
  const resultsPerPageOptions = [
    { value: '10', label: '10' },
    { value: '20', label: '20' },
    { value: '50', label: '50' },
  ];

  return (
    <div className="pagination">
      <div className="navigation">
        <Button size="medium" type="secondary" disabled>
          &lt;&lt;
        </Button>
        <Button size="medium" type="primary" disabled>
          &lt;
        </Button>
        <span className="page-info">Page 1 of 4</span>
        <Button size="medium" type="primary">
          &gt;
        </Button>
        <Button size="medium" type="secondary">
          &gt;&gt;
        </Button>
      </div>
      <Dropdown
        className="results-filter"
        label="Results per page"
        id="results-per-page"
        options={resultsPerPageOptions}
      />
    </div>
  );
};

export default Pagination;
