// frontend-angular/src/app/features/recipes/recipe-detail/recipe-section/recipe-instructions/recipe-instructions.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-recipe-instructions',
  standalone: true,
  imports: [CommonModule],
  templateUrl: 'recipe-instructions.component.html',
})
export class RecipeInstructionsComponent {
  @Input() instructions: string[] = [];
}

<div class="recipe-instructions">
  <label>Instructions</label>
  <ol class="instructions-steps">
    <li class="instruction-step" *ngFor="let instruction of instructions">
      {{ instruction }}
    </li>
  </ol>
</div>

// frontend-react/src/components/RecipeInstructions.tsx
import type React from 'react';

interface RecipeInstructionsProps {
  instructions: string[];
}

const RecipeInstructions: React.FC<RecipeInstructionsProps> = ({ instructions }) => {
  return (
    <div className="recipe-instructions">
      <label htmlFor="instructions">Instructions</label>
      <ol className="instructions-steps">
        {instructions.map((instruction) => (
          <li className="instruction-step" key={instruction}>{instruction}</li>
        ))}
      </ol>
    </div>
  );
};

export default RecipeInstructions;
