// frontend-angular/src/app/features/recipes/recipe-detail/review-section/review-form/review-form.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { StarRatingComponent } from '@shared/components/star-rating/star-rating.component';
import { AppButtonComponent } from '@shared/components/app-button/app-button.component';

@Component({
  selector: 'app-review-form',
  standalone: true,
  imports: [CommonModule, FormsModule, StarRatingComponent, AppButtonComponent],
  templateUrl: 'review-form.component.html',
})
export class ReviewFormComponent {
  @Input() rating = 0;
  @Input() comment = '';
  @Input() submitting = false;

  @Output() submitReview = new EventEmitter<{rating: number, comment: string}>();

  onSubmit(): void {
    if (!this.rating || !this.comment.trim() || this.submitting) {
      return;
    }

    this.submitReview.emit({
      rating: this.rating,
      comment: this.comment
    });
  }
}

<form class="review-form" (submit)="onSubmit()">
  <label>Leave a Review</label>
  <div class="rating">
    <label>Rating:</label>
    <app-star-rating
      [(rating)]="rating"
      [readOnly]="false">
    </app-star-rating>
  </div>
  <div class="comment">
    <label for="comment">Comment:</label>
    <textarea
      class="input-textarea"
      id="comment"
      name="comment"
      rows="4"
      [(ngModel)]="comment"
      placeholder="Write your review here...">
        </textarea>
  </div>
  <app-button
    type="primary"
    [disabled]="!rating || !comment.trim() || submitting"
    (buttonClick)="onSubmit()">
    Submit Review
  </app-button>
</form>

// frontend-react/src/components/ReviewForm.tsx
import type React from 'react';
import useReviewForm from '@hooks/useReviewForm';
import StarRating from '@components/StarRating';
import Button from '@components/Button';

interface ReviewFormProps {
  recipeId: string;
  onSubmit: (rating: number, content: string) => Promise<void>;
}

const ReviewForm: React.FC<ReviewFormProps> = ({ onSubmit }) => {
  const {
    rating,
    comment,
    error,
    loading,
    handleRatingChange,
    handleCommentChange,
    handleSubmit,
  } = useReviewForm({ onSubmit });

  return (
    <form className="review-form" onSubmit={handleSubmit}>
      <label htmlFor="review">Leave a Review</label>
      <div className="rating">
        <label htmlFor="rating">Rating:</label>
        <StarRating rating={rating} name="review-form" onRatingChange={handleRatingChange} />
      </div>
      <div className="comment">
        <label htmlFor="comment">Comment:</label>
        <textarea
          className="input-textarea"
          id="comment"
          name="comment"
          rows={4}
          placeholder="Write your review here..."
          value={comment}
          onChange={handleCommentChange}
        />
      </div>
      {error && <p className="error-message">{error}</p>}
      <Button size="medium" type="primary" htmlType="submit" disabled={loading}>
        {loading ? 'Submitting...' : 'Submit Review'}
      </Button>
    </form>
  );
};

export default ReviewForm;
