// frontend-angular/src/app/features/recipes/recipe-detail/review-section/reviews-list/review/review.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { StarRatingComponent } from '@shared/components/star-rating/star-rating.component';
import { AppButtonComponent } from '@shared/components/app-button/app-button.component';
import { ReviewType } from '@models/review.model';

@Component({
  selector: 'app-review',
  standalone: true,
  imports: [CommonModule, FormsModule, StarRatingComponent, AppButtonComponent],
  templateUrl: 'review.component.html',
})
export class ReviewComponent {
  @Input() review!: ReviewType;
  @Input() userName = '';
  @Input() canEdit = false;
  @Input() isEditing = false;
  @Input() formattedDate = '';
  @Input() editRating = 0;
  @Input() editComment = '';

  @Output() startEditing = new EventEmitter<ReviewType>();
  @Output() cancelEditing = new EventEmitter<void>();
  @Output() saveReview = new EventEmitter<{rating: number, content: string}>();

  onStartEditing(): void {
    this.startEditing.emit(this.review);
  }

  onCancel(): void {
    this.cancelEditing.emit();
  }

  onSave(): void {
    this.saveReview.emit({
      rating: this.editRating,
      content: this.editComment
    });
  }
}

<div class="review">
  <div class="review-header">
    <div class="rating">
      <label>{{ userName }}:</label>

      <app-star-rating
        *ngIf="!isEditing"
        [rating]="review.rating"
        [readOnly]="true">
      </app-star-rating>

      <app-star-rating
        *ngIf="isEditing"
        [(rating)]="editRating"
        [readOnly]="false">
      </app-star-rating>
    </div>
    <div class="date-edit">
      <ng-container *ngIf="canEdit">
        <ng-container *ngIf="!isEditing">
          <app-button
            type="secondary"
            size="small"
            (buttonClick)="onStartEditing()">
            Edit
          </app-button>
        </ng-container>

        <ng-container *ngIf="isEditing">
          <app-button
            type="primary"
            size="small"
            (buttonClick)="onSave()">
            Save
          </app-button>
          <app-button
            type="tertiary"
            size="small"
            (buttonClick)="onCancel()">
            Cancel
          </app-button>
        </ng-container>
      </ng-container>

      <div class="review-date">{{ formattedDate }}</div>
    </div>
  </div>

  <p *ngIf="!isEditing" class="review-comment">{{ review.content }}</p>

  <textarea
    *ngIf="isEditing"
    class="input-textarea review-comment-edit"
    [(ngModel)]="editComment">
      </textarea>
</div>

// frontend-react/src/components/Review.tsx
import { forwardRef } from 'react';
import useReview from '@hooks/useReview';
import StarRating from '@components/StarRating';
import Button from '@components/Button';

interface ReviewProps {
  id: string;
  userId: string;
  rating: number;
  date: string;
  comment: string;
  canEdit: boolean;
  onSave: (reviewId: string, rating: number, content: string) => void;
}

const Review = forwardRef<HTMLDivElement, ReviewProps>(({ id, userId, rating, date, comment, canEdit, onSave }, ref) => {
  const {
    isEditing,
    editedComment,
    editedRating,
    setEditedComment,
    setEditedRating,
    handleEditClick,
    handleCancelClick,
    handleSaveClick,
    userName,
  } = useReview({ id, userId, comment, rating, onSave });

  return (
    <div ref={ref} className="review">
      <div className="review-header">
        <div className="rating">
          <label htmlFor={`review-${id}`}>{userName}:</label>
          <StarRating
            rating={editedRating}
            name={`review-${id}`}
            readOnly={!isEditing}
            onRatingChange={setEditedRating}
          />
        </div>
        <div className="date-edit">
          {canEdit && (
            !isEditing ? (
              <Button size="small" type="primary" onClick={handleEditClick}>
                Edit
              </Button>
            ) : (
              <>
                <Button size="small" type="primary" onClick={handleSaveClick}>
                  Save
                </Button>
                <Button size="small" type="tertiary" onClick={handleCancelClick}>
                  Cancel
                </Button>
              </>
            )
          )}
          <div className="review-date">{date}</div>
        </div>
      </div>
      {isEditing ? (
        <textarea
          className="input-textarea review-comment-edit"
          value={editedComment}
          onChange={(e) => setEditedComment(e.target.value)}
        />
      ) : (
        <p className="review-comment">{comment}</p>
      )}
    </div>
  );
});

export default Review;
