// frontend-react/src/components/RecipeHeader.tsx
import type React from 'react';

interface RecipeHeaderProps {
  title: string;
  isFavorite: boolean;
  onFavoriteChange: () => void;
}

const RecipeHeader: React.FC<RecipeHeaderProps> = ({ title, isFavorite, onFavoriteChange }) => {
  return (
    <div className="recipe-header">
      <h1>{title}</h1>
      <div className="recipe-actions">
        <div className="input-favorite">
          <input
            type="checkbox"
            id="favorite"
            className="favorite-checkbox"
            checked={isFavorite}
            onChange={onFavoriteChange}
          />
          <label htmlFor="favorite" className="favorite-label" />
        </div>
      </div>
    </div>
  );
};

export default RecipeHeader;

// frontend-angular/src/app/features/recipes/recipe-detail/recipe-main-section/recipe-header/recipe-header.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-recipe-header',
  standalone: true,
  imports: [CommonModule],
 templateUrl: 'recipe-header.component.html'
})
export class RecipeHeaderComponent {
  @Input() title = '';
  @Input() recipeId = 0;
  @Input() isFavorite = false;
  @Input() isAuthenticated = false;

  @Output() toggleFavorite = new EventEmitter<void>();

  onToggleFavorite(): void {
    this.toggleFavorite.emit();
  }
}

<div class="recipe-header">
  <h1>{{ title }}</h1>
  <div class="recipe-actions">
    <div class="input-favorite" *ngIf="isAuthenticated">
      <input
        type="checkbox"
        [id]="'favorite-' + recipeId"
        class="favorite-checkbox"
        [checked]="isFavorite">
      <label
        [for]="'favorite-' + recipeId"
        class="favorite-label"
        (click)="onToggleFavorite()">
      </label>
    </div>
  </div>
</div>
