// frontend-react/src/components/Card.tsx
import type React from 'react';
import { Link } from 'react-router-dom';
import Image from './Image';
import Favorite from './Favorite';

export interface CardProps {
  id: string;
  image: string;
  title: string;
  readyInMinutes: number;
  healthScore: number;
}

const Card: React.FC<CardProps> = ({ id, image, title, readyInMinutes, healthScore }) => {
  return (
    <div className="card">
      <Link to={`/recipe/${id}`}>
        <Image src={image} alt={title} />
        <div className="title">{title}</div>
      </Link>
      <div className="details">
        <span className="prep-time">Preparation time: {readyInMinutes}</span>
        <span className="score">Score: {healthScore}</span>
      </div>
      <Favorite id={id} />
    </div>
  );
};

export default Card;

// frontend-angular/src/app/shared/components/card/card.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RecipeType } from '@models/recipe.model';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  standalone: true,
  imports: [CommonModule, RouterModule]
})
export class CardComponent {
  @Input() recipe!: RecipeType;
  @Input() isFavorite = false;

  @Output() toggleFavorite = new EventEmitter<number>();

  onToggleFavorite(event: Event): void {
    event.preventDefault();
    event.stopPropagation();
    this.toggleFavorite.emit(this.recipe.id);
  }
}

<div class="card">
  <a [routerLink]="['/recipe', recipe.id]">
    <img [src]="recipe.image" [alt]="recipe.title + ' Image'">
    <div class="title">{{ recipe.title }}</div>
    <div class="details">
      <span class="prep-time">Preparation time: {{ recipe.readyInMinutes }}</span>
      <span class="score">Score: {{ recipe.healthScore }}</span>
    </div>
  </a>
  <div class="input-favorite">
    <input
      type="checkbox"
      [id]="'favorite-' + recipe.id"
      class="favorite-checkbox"
      [checked]="isFavorite">
    <label
      [for]="'favorite-' + recipe.id"
      class="favorite-label"
      (click)="onToggleFavorite($event)">
    </label>
  </div>
</div>
