// frontend-react/src/components/RecipeSection.tsx
import type React from 'react';
import type { Ingredient } from './Ingredient';
import ServingsFilter from './ServingsFilter';
import IngredientsList from './IngredientsList';
import RecipeInfo from './RecipeInfo';
import RecipeInstructions from './RecipeInstructions';

interface RecipeSectionProps {
  servings: number;
  ingredients: Ingredient[];
  readyInMinutes: number;
  healthScore: number;
  cuisines: string[];
  dishTypes: string[];
  diets: string[];
  instructions: string[];
}

const RecipeSection: React.FC<RecipeSectionProps> = ({
                                                       servings,
                                                       ingredients,
                                                       readyInMinutes,
                                                       healthScore,
                                                       cuisines,
                                                       dishTypes,
                                                       diets,
                                                       instructions,
                                                     }) => {
  return (
    <div className="recipe-section">
      <div className="ingredients-container">
        <ServingsFilter servings={servings} />
        <IngredientsList ingredients={ingredients} />
      </div>
      <div className="recipe-wrapper">
        <RecipeInfo
          readyInMinutes={readyInMinutes}
          healthScore={healthScore}
          cuisines={cuisines}
          dishTypes={dishTypes}
          diets={diets}
        />
        <RecipeInstructions instructions={instructions} />
      </div>
    </div>
  );
};

export default RecipeSection;

// frontend-angular/src/app/features/recipes/recipe-detail/recipe-section/recipe-section.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RecipeIngredientsComponent } from '@features/recipes/recipe-detail/recipe-section/recipe-wrapper/recipe-ingredients/recipe-ingredients.component';
import { RecipeWrapperComponent } from '@features/recipes/recipe-detail/recipe-section/recipe-wrapper/recipe-wrapper.component';
import { IngredientType } from '@models/recipe.model';

@Component({
  selector: 'app-recipe-section',
  standalone: true,
  imports: [CommonModule, RecipeIngredientsComponent, RecipeWrapperComponent],
  templateUrl: 'recipe-section.component.html',
})
export class RecipeSectionComponent {
  @Input() ingredients: IngredientType[] = [];
  @Input() servings = 1;
  @Input() originalServings = 1;
  @Input() readyInMinutes = 0;
  @Input() healthScore = 0;
  @Input() cuisines: string[] = [];
  @Input() dishTypes: string[] = [];
  @Input() diets: string[] = [];
  @Input() instructions: string[] = [];
}

<div class="recipe-section">
  <app-recipe-ingredients
    [ingredients]="ingredients"
    [servings]="servings"
    [originalServings]="originalServings">
  </app-recipe-ingredients>

  <app-recipe-wrapper
    [readyInMinutes]="readyInMinutes"
    [healthScore]="healthScore"
    [cuisines]="cuisines"
    [dishTypes]="dishTypes"
    [diets]="diets"
    [instructions]="instructions">
  </app-recipe-wrapper>
</div>
