// frontend-react/src/components/RecipeInfo.tsx
import type React from 'react';

interface RecipeInfoProps {
  readyInMinutes: number;
  healthScore: number;
  cuisines: string[];
  dishTypes: string[];
  diets: string[];
}

const RecipeInfo: React.FC<RecipeInfoProps> = ({
                                                 readyInMinutes,
                                                 healthScore,
                                                 cuisines,
                                                 dishTypes,
                                                 diets,
                                               }) => {
  return (
    <div className="recipe-info">
      <div className="stats">
        <div className="stat">
          <label htmlFor="preparation-time">Preparation Time</label>
          <span>{readyInMinutes} minutes</span>
        </div>
        <div className="stat">
          <label htmlFor="health-score">Health Score</label>
          <span>{healthScore}</span>
        </div>
      </div>
      <div className="info">
        <div className="info-item">
          <label htmlFor="cuisines">Cuisines:</label>
          <span>{cuisines.join(', ')}</span>
        </div>
        <div className="info-item">
          <label htmlFor="dish-types">Dish Types:</label>
          <span>{dishTypes.join(', ')}</span>
        </div>
        <div className="info-item">
          <label htmlFor="diets">Diets:</label>
          <span>{diets.join(', ')}</span>
        </div>
      </div>
    </div>
  );
};

export default RecipeInfo;

// frontend-angular/src/app/features/recipes/recipe-detail/recipe-section/recipe-wrapper/recipe-info/recipe-info.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-recipe-info',
  standalone: true,
  imports: [CommonModule],
  templateUrl: 'recipe-info.component.html',
})
export class RecipeInfoComponent {
  @Input() readyInMinutes = 0;
  @Input() healthScore = 0;
  @Input() cuisines: string[] = [];
  @Input() dishTypes: string[] = [];
  @Input() diets: string[] = [];
}

<div class="recipe-info">
  <div class="stats">
    <div class="stat">
      <label>Preparation Time</label>
      <span>{{ recipeUI.readyInMinutes$ | async }} minutes</span>
    </div>
    <div class="stat">
      <label>Health Score</label>
      <span>{{ recipeUI.healthScore$ | async }}</span>
    </div>
  </div>

  <div class="info">
    <div class="info-item" *ngIf="(recipeUI.cuisines$ | async)?.length">
      <label>Cuisines:</label>
      <span> {{ (recipeUI.cuisines$ | async)?.join(', ') }}</span>
    </div>
    <div class="info-item" *ngIf="(recipeUI.dishTypes$ | async)?.length">
      <label>Dish Types:</label>
      <span> {{ (recipeUI.dishTypes$ | async)?.join(', ') }}</span>
    </div>
    <div class="info-item" *ngIf="(recipeUI.diets$ | async)?.length">
      <label>Diets:</label>
      <span> {{ (recipeUI.diets$ | async)?.join(', ') }}</span>
    </div>
  </div>
</div>
