// frontend-react/src/components/Loader.tsx
import type React from 'react';
import '@styles/components/_loader.scss';

interface LoaderProps {
  message?: string;
  size?: 'small' | 'medium' | 'large';
}

const Loader: React.FC<LoaderProps> = ({ message = 'Loading...', size = 'medium' }) => {
  return (
    <div className={`loader-container loader-${size}`}>
      <div className="loader-spinner" />
      {message && <p className="loader-message">{message}</p>}
    </div>
  );
};

export default Loader;

// frontend-angular/src/app/shared/components/loader/loader.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-loader',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './loader.component.html',
})
export class LoaderComponent {
  @Input() message = 'Loading...';
  @Input() size: 'small' | 'medium' | 'large' = 'medium';
}

<div class="loader-container" [ngClass]="'loader-' + size">
  <div class="loader-spinner"></div>
  <p *ngIf="message" class="loader-message">{{ message }}</p>
</div>
